// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package test is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	Tell
*/
package test

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Tell struct {
	Msg              *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Tell) Reset()         { *m = Tell{} }
func (m *Tell) String() string { return proto.CompactTextString(m) }
func (*Tell) ProtoMessage()    {}

func (m *Tell) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
}
